import { execFileSync } from "child_process";
import { existsSync } from "fs";
import { join } from "path";

export type GitMode = "branch" | "push" | "commit" | "none";

export interface GitResult {
  attempted: boolean;
  ok: boolean;
  branch?: string;
  pushed: boolean;
  /** Human-readable summary for the report/CLI. */
  message: string;
}

const DEFAULT_BRANCH = "consentify-setup";
const COMMIT_MESSAGE =
  "feat: set up Consentify consent management\n\nRemoved the existing consent tool / third-party tracking scripts and\nwired up the Consentify consent banner. Generated by consentify-migrate.";

/** Run a git command in `cwd`, returning trimmed stdout. Throws on failure. */
function git(cwd: string, args: string[]): string {
  return execFileSync("git", args, {
    cwd,
    encoding: "utf-8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

/** Same, but returns null instead of throwing (for best-effort checks). */
function gitSafe(cwd: string, args: string[]): string | null {
  try {
    return git(cwd, args);
  } catch {
    return null;
  }
}

export function isGitRepo(dir: string): boolean {
  if (existsSync(join(dir, ".git"))) return true;
  return gitSafe(dir, ["rev-parse", "--is-inside-work-tree"]) === "true";
}

export function hasRemote(dir: string): boolean {
  const remotes = gitSafe(dir, ["remote"]);
  return !!remotes && remotes.length > 0;
}

export function currentBranch(dir: string): string | null {
  return gitSafe(dir, ["rev-parse", "--abbrev-ref", "HEAD"]);
}

function branchExists(dir: string, branch: string): boolean {
  return (
    gitSafe(dir, ["rev-parse", "--verify", "--quiet", `refs/heads/${branch}`]) !==
    null
  );
}

/**
 * Stage the given files, commit them on a dedicated branch, and (optionally)
 * push. Only the files we changed are staged — we never `git add -A`, so a
 * customer's pre-existing uncommitted work is left untouched.
 *
 * `files` should be absolute paths; they're converted to repo-relative.
 */
export function commitAndPush(
  repoDir: string,
  files: string[],
  mode: GitMode,
): GitResult {
  if (mode === "none") {
    return { attempted: false, ok: true, pushed: false, message: "Git skipped (--git=none)" };
  }

  if (!isGitRepo(repoDir)) {
    return {
      attempted: false,
      ok: false,
      pushed: false,
      message: "Not a git repository — skipped commit",
    };
  }

  if (files.length === 0) {
    return { attempted: false, ok: true, pushed: false, message: "No file changes to commit" };
  }

  try {
    const startBranch = currentBranch(repoDir);
    let targetBranch = startBranch ?? DEFAULT_BRANCH;

    // For branch mode, create/switch to the dedicated branch.
    if (mode === "branch") {
      targetBranch = DEFAULT_BRANCH;
      if (branchExists(repoDir, DEFAULT_BRANCH)) {
        git(repoDir, ["checkout", DEFAULT_BRANCH]);
      } else {
        git(repoDir, ["checkout", "-b", DEFAULT_BRANCH]);
      }
    }

    // Stage only our files (repo-relative paths).
    git(repoDir, ["add", "--", ...files]);

    // Nothing staged? (e.g. files already committed) — bail gracefully.
    const staged = gitSafe(repoDir, ["diff", "--cached", "--name-only"]);
    if (!staged) {
      return {
        attempted: true,
        ok: true,
        pushed: false,
        branch: targetBranch,
        message: "Nothing to commit (already up to date)",
      };
    }

    git(repoDir, ["commit", "-m", COMMIT_MESSAGE]);

    // Push if requested.
    let pushed = false;
    let message = `Committed on ${targetBranch}`;
    if (mode === "branch" || mode === "push") {
      if (!hasRemote(repoDir)) {
        message = `Committed on ${targetBranch} (no remote — push manually)`;
      } else {
        try {
          git(repoDir, ["push", "-u", "origin", targetBranch]);
          pushed = true;
          message = `Committed + pushed ${targetBranch}`;
        } catch (err) {
          const detail = err instanceof Error ? err.message.split("\n")[0] : String(err);
          message = `Committed on ${targetBranch}, push failed: ${detail}`;
        }
      }
    }

    return { attempted: true, ok: true, pushed, branch: targetBranch, message };
  } catch (err) {
    const detail = err instanceof Error ? err.message.split("\n")[0] : String(err);
    return { attempted: true, ok: false, pushed: false, message: `Git error: ${detail}` };
  }
}
